<?php
if (empty($_GET['act']))
{include"beranda.php";}
else{
	switch($_GET['act']){

        case('profil'): include('profil.php');
        break;
        case('absen'): include('absen.php');
        break;
        case('absen_laporan'): include('absen_laporan.php');
        break;
        case('absen_rincian'): include('absen_rincian.php');
        break;
        case('absen_edit'): include('absen_edit.php');
        break;
        case('absen_input'): include('absen_input.php');
        break;
        case('absen_input2'): include('absen_input2.php');
        break;
        case('guru_nilai_rekapitulasi'): include('guru_nilai_rekapitulasi.php');
        break;
        case('guru_nilai_input'): include('guru_nilai_input.php');
        break;
        case('guru_nilai_edit'): include('guru_nilai_edit.php');
        break;
        case('guru_nilai_input2'): include('guru_nilai_input2.php');
        break;
        case('guru_nilai_rincian'): include('guru_nilai_rincian.php');
        break;
        case('nilai_rekapitulasi'): include('nilai_rekapitulasi.php');
        break;
        case('nilai_input'): include('nilai_input.php');
        break;
        case('nilai_edit'): include('nilai_edit.php');
        break;
        case('nilai_input2'): include('nilai_input2.php');
        break;
        case('nilai_rincian'): include('nilai_rincian.php');
        break;
        case('cetak_guru'): include('cetak_guru.php');
        break;
        case('data_siswa'): include('data_siswa.php');
    	break;
        case('data_guru'): include('data_guru.php');
        break;
        case('data_jadwal'): include('data_jadwal.php');
        break;
        case('data_kelas'): include('data_kelas.php');
        break;
        case('data_mengajar'): include('data_mengajar.php');
        break;
        case('data_mata_pelajaran'): include('data_mata_pelajaran.php');
        break;
        case('data_nilai'): include('data_nilai.php');
        break;
        case('data_presensi'): include('data_presensi.php');
        break;
        case('data_tata_usaha'): include('data_tata_usaha.php');
        break;
        case('tambah_anggota'): include('tambah_anggota.php');
        break;
        case('tambah_siswa'): include('tambah_siswa.php');
        break;
        case('tambah_guru'): include('tambah_guru.php');
        break;
        case('tambah_jadwal_pelajaran'): include('tambah_jadwal_pelajaran.php');
        break;
        case('tambah_kelas'): include('tambah_kelas.php');
        break;
        case('tambah_mata_pelajaran'): include('tambah_mata_pelajaran.php');
        break;
        case('tambah_tata_usaha'): include('tambah_tata_usaha.php');
        break;
        case('edit_guru'): include('edit_guru.php');
        break;
        case('edit_jadwal'): include('edit_jadwal.php');
        break;
        case('edit_kelas'): include('edit_kelas.php');
        break;
        case('edit_mapel'): include('edit_mapel.php');
        break;
        case('edit_nilai'): include('edit_nilai.php');
        break;
        case('edit_siswa'): include('edit_siswa.php');
        break;
        case('edit_tata_usaha'): include('edit_tata_usaha.php');
        break;
        case('laporan'): include('laporan.php');
    	break;
        case('laporan_siswa'): include('laporan_siswa.php');
        break;
        case('laporan_guru'): include('laporan_guru.php');
        break;
        case('laporan_jadwal'): include('laporan_jadwal.php');
        break;
        case('laporan_kelas'): include('laporan_kelas.php');
        break;
        case('laporan_mata_pelajaran'): include('laporan_mata_pelajaran.php');
        break;
        case('laporan_nilai'): include('laporan_nilai.php');
        break;
        case('laporan_nilai_rincian'): include('laporan_nilai_rincian.php');
        break;
        case('laporan_tata_usaha'): include('laporan_tata_usaha.php');
        break;
        case('transaksi'): include('transaksi.php');
        break;
        case('tambah_transaksi'): include('tambah_transaksi.php');
        break;
        case('transaksi_kembali'): include('transaksi_kembali.php');
        break;
        case('ganti_password'): include('ganti_password.php');
        break;
	default:include('beranda.php');
	}
}
?>
